version: 2
jobs:
    build:
    docker:
      - image: nginx:alpine
        steps:
        - checkout  
        - run : echo "hellp world"
        - run: |
          docker build -f .
          docker login https://cloud.docker.com/repository/docker/fhdockerlab/ -u fhdockerlab -p Fasank12!23
          docker tag simple-html:v1 fhdockerlab/simple-html:v2
          docker push fhdockerlab/simple-html:v2

workflows:
  version: 2
  build:
    jobs:
      - build
                     