version: 2
jobs:
  build:
    working_directory: ~/repo
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: ngnix:alpine # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - run:
          name: Build application Docker image
          command: |
            docker build -f .
      - run:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

            docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            docker tag fhdockerlab/simple-html fhdockerlab/simple-html:v2
            docker push fhdockerlab/simple-html:v2
            fi

workflows:
  version: 2
  build:
    jobs:
      - build
                     