version: 2
jobs:
    build:
    docker:
      - image: nginx:alpine
        steps:
        - checkout  
        - run : echo "hellp world"
        

workflows:
  version: 2
  build:
    jobs:
      - build
                     